name: Account Request Close

on:
  issues:
    types:
      - labeled

jobs:
  # When an issue created by account management authorization form is updated with label
  # ACCOUNT_APPROVED or ACCOUNT_REJECTED - # Account was approved or rejected
  request-approve:
    if: github.event.label.name == 'ACCOUNT_APPROVED'
    runs-on: ubuntu-20.04
    permissions:
      issues: write
    steps:
      - name: Add comment
        run: gh issue comment "$NUMBER" --body "$BODY"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
          NUMBER: ${{ github.event.issue.number }}
          BODY: >
            Account management APPROVED
        # Auto close issue with comment

  request-reject:
    if: github.event.label.name == 'ACCOUNT_REJECTED'
    runs-on: ubuntu-20.04
    permissions:
      issues: write
    steps:
      - name: Add comment
        run: gh issue comment "$NUMBER" --body "$BODY"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
          NUMBER: ${{ github.event.issue.number }}
          BODY: >
            Account management REJECTED
