name: Account Request Approved

on:
  issues:
    types:
      - labeled

jobs:
  # When ACCOUNT_APPROVED label is added to account management request
  request-approved:
    if: github.event.label.name == 'ACCOUNT_APPROVED'
    runs-on: ubuntu-20.04
    permissions:
      issues: write
    steps:
      - name: Notify Blossom Sysdevs about Approved Account
        run: gh issue comment "$NUMBER" --body "$BODY"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
          NUMBER: ${{ github.event.issue.number }}
          BODY: >
            Account management request APPROVED by Blossom Management.
            @blossom-sysdevs please review and submit Account Management Authorization Form.